version: '3.4'

services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    build:
      context: ./apiGateway/userMicroService
      dockerfile: ./Dockerfile
  productmicroservice:
    image: ${DOCKER_REGISTRY-}productmicroservice
    build:
      context: ./apiGateway/productMicroService
      dockerfile: ./Dockerfile
