version: '3.4'

services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    build:
      context: ./apiGateway/userMicroService
      dockerfile: ./Dockerfile
    ports:
      - "5137:80"
  usermicroservice-tests:
    image: ${DOCKER_REGISTRY-}usermicroservice
    build:
      context: ./apiGateway/userMicroServices.Unit
      dockerfile: ./Dockerfile
