version: '3.4'

services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    ports:
      - "5296:80"
    environment:
      - DOTNET_URLS=http://+:5296
    build:
      context: ./apiGateway/userMicroService
      dockerfile: ./Dockerfile
      
  productmicroservice:
    image: ${DOCKER_REGISTRY-}productmicroservice
    ports:
      - "5112:80"
    build:
      context: ./apiGateway/productMicroService
      dockerfile: ./Dockerfile
