name: CI/CD Pipeline
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Data from main branch
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          sudo docker-compose -f docker-compose.yml build 
          sudo docker save usermicroservice > usermicroservice.tar 
          sudo docker save productmicroservice > productmicroservice.tar

      - name: Upload Docker Images as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerImages
          path: |
            usermicroservice.tar
            productmicroservice.tar
        
      - name: Upload Docker Image via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            scp -o StrictHostKeyChecking=no usermicroservice.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo docker load -i /root/usermicroservice.tar'
            
      - name: Remove Docker Images
        run: sudo docker image prune -a -f
