name: CI/CD Pipeline
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  save-build-to-images:
    runs-on: self-hosted
    steps:
      - name: Pull Data from main branch
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          sudo docker-compose -f docker-compose.yml build 
          sudo docker save usermicroservice > usermicroservice.tar 
          sudo docker save productmicroservice > productmicroservice.tar
      - name: Transfer Docker Image to Server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no usermicroservice.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Load Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker rmi $(docker images -a -q)
            sudo docker load -i /root/usermicroservice.tar
            docker-compose up -d
            
      - name: Remove Docker Images
        run: sudo docker image prune -a -f
