name: CI/CD Pipeline
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Data from main branch
        uses: actions/checkout@v2

      - name: Build Docker images
        run: sudo docker-compose -f docker-compose.yml build -t micoserviceunit:tag .| docker save my-image:tag > my-image.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: userMicroService.Unit.Tests
          path: my-image.tar
        
      - name: Remove Docker Images
        run: sudo docker image prune -a -f
