name: Test builds on develop branch
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Test
        run: dotnet test --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
