name: Test builds on develop branch
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  run-tests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: apiGateway/userMicroServices.Unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test userMicroServices.Unit.csproj --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
